### ISSUE TITLE
Request: Update PyPi package

### ISSUE THREAD

**Issue by kaukrise** [pygridtools/gridmap#74]
Hello,

First of all thank you for a fantastic package, it is extremely useful for our research where we have to process large amounts of data. We are about to release a Python package for one of our tools and gridmap is a dependency for parallelising the most computationally intensive calculation.

Currently, the latest available gridmap package on PyPi is version 0.13.0, but the code is not up to date with the code in the GitHub repository. Hence we were wondering if it would be possible to give gridmap a version bump to 0.14.0 and upload an updated package to PyPi, so our users can make use of the latest fixes and improvements (without having to install manually from GitHub)?

Thank you very much in advance!

Kai

**Comment by desilinguist** [comment]
Thanks for the kind words, Kai. I’m actually planning to make a few changes in terms of compatibility with newer versions of dependencies (e.g., psutil). So, I’ll be making a new version before the end of the year anyway.

**Comment by kaukrise** [comment]
That sounds great, thanks a lot!

**Comment by desilinguist** [comment]
New version released.

**Comment by vaquerizaslab** [comment]
Great, I'm going to check it out! And thanks!
