### ISSUE TITLE
Update anaconda python support

### ISSUE THREAD

**Issue by labradon** [pygridtools/gridmap#84]
Dear maintainers,
I hope to reach the correct persons here. I'm trying to integrate gridmap via the anaconda package manager for python 3.8. However, conda does only list packages for gridmap up to python 3.6 (https://anaconda.org/anaconda/gridmap/files), which forces me to take the workaround using pip. This is okay for now, but I want to clean this up in the future.
Many thanks to anyone who can fix this!

**Comment by desilinguist** [comment]
Hi @labradon we didn’t create the conda package. It seems to have been created by the anaconda maintainers - so I think they are the ones who should update their package.

**Comment by labradon** [comment]
Okay, thanks for the fast reply!
